### PR TITLE
Update reagent and change deprecated calls to reagent.core

### PR DESCRIPTION
**Pull request by AndreaCrotti**

### CODE REVIEW

**Comment by oliyh** [comment]
Hi @AndreaCrotti 

Anything I should infer from 'try'? Any concerns?

Cheers

**Comment by AndreaCrotti** [comment]
Yes I guess there should be issues since the latest reagent moved a few things around, which I noticed when trying to bump the reagent library on one of our projects.

**Comment by AndreaCrotti** [comment]
Just pushed this to get circle ci running at least, but yeah I think I know what changes are required anyway.

**Comment by oliyh** [comment]
Looks pretty good now, ready to merge?

**Pull request merged**
